# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'

  # Pods for RxSwiftExample

  target 'RxSwiftExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftExampleUITests' do
    # Pods for testing
  end

end
